language: java
jdk:
  - oraclejdk8
  - oraclejdk9
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer
install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
  - data
